import type { PolicyStatus, ProviderCategory } from '@shadowscan/shared';

// THE AI PROVIDER REGISTRY This file is data, not logic.
export interface ProviderSeed {
  key: string;
  name: string;
  vendor: string;
  category: ProviderCategory;
  domains: string[];
  riskWeight: number;
  defaultPolicy: PolicyStatus;
  dataRegion: string;
  trainsOnUserData: boolean;
  notes: string;
}

export const AI_PROVIDERS: readonly ProviderSeed[] = [
  {
    key: 'openai-chatgpt',
    name: 'ChatGPT',
    vendor: 'OpenAI',
    category: 'assistant',
    domains: ['chatgpt.com', 'chat.openai.com', 'openai.com'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes:
      'Free and Plus tiers train on conversations unless the user opts out. Team/Enterprise do not.',
  },
  {
    key: 'openai-api',
    name: 'OpenAI API',
    vendor: 'OpenAI',
    category: 'api',
    domains: ['api.openai.com', 'platform.openai.com'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: false,
    notes: 'Direct API traffic. Often indicates an unmanaged application, not a browser user.',
  },
  {
    key: 'anthropic-claude',
    name: 'Claude',
    vendor: 'Anthropic',
    category: 'assistant',
    domains: ['claude.ai', 'claude.com'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: false,
    notes: 'Does not train on conversations by default on consumer or commercial tiers.',
  },
  {
    key: 'anthropic-api',
    name: 'Anthropic API',
    vendor: 'Anthropic',
    category: 'api',
    domains: ['api.anthropic.com', 'console.anthropic.com'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: false,
    notes: 'Direct API traffic.',
  },
  {
    key: 'google-gemini',
    name: 'Gemini',
    vendor: 'Google',
    category: 'assistant',
    domains: ['gemini.google.com', 'bard.google.com', 'aistudio.google.com'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes: 'Consumer Gemini conversations may be reviewed by humans for quality.',
  },
  {
    key: 'microsoft-copilot',
    name: 'Microsoft Copilot',
    vendor: 'Microsoft',
    category: 'assistant',
    domains: ['copilot.microsoft.com', 'm365.cloud.microsoft', 'copilot.cloud.microsoft'],
    riskWeight: 1,
    defaultPolicy: 'approved',
    dataRegion: 'US',
    trainsOnUserData: false,
    notes:
      'Commercial Data Protection keeps prompts inside the tenant boundary when the user is signed in with a work account.',
  },
  {
    key: 'meta-ai',
    name: 'Meta AI',
    vendor: 'Meta',
    category: 'assistant',
    domains: ['meta.ai'],
    riskWeight: 3,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes: 'Consumer service with no enterprise data-processing agreement.',
  },
  {
    key: 'xai-grok',
    name: 'Grok',
    vendor: 'xAI',
    category: 'assistant',
    domains: ['grok.com', 'x.ai'],
    riskWeight: 3,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes: 'Consumer tier trains on conversations by default.',
  },
  {
    key: 'mistral-lechat',
    name: 'Le Chat',
    vendor: 'Mistral AI',
    category: 'assistant',
    domains: ['chat.mistral.ai', 'mistral.ai', 'api.mistral.ai'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'FR',
    trainsOnUserData: false,
    notes: 'EU-hosted. Often the lowest-friction approval for GDPR-bound teams.',
  },
  {
    key: 'cohere',
    name: 'Cohere',
    vendor: 'Cohere',
    category: 'api',
    domains: ['cohere.com', 'cohere.ai'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'CA',
    trainsOnUserData: false,
    notes: '',
  },

  // ------------------------------- non-allied jurisdiction / high scrutiny ---
  {
    key: 'deepseek',
    name: 'DeepSeek',
    vendor: 'DeepSeek',
    category: 'assistant',
    domains: ['deepseek.com', 'chat.deepseek.com', 'api.deepseek.com'],
    riskWeight: 3,
    defaultPolicy: 'blocked',
    dataRegion: 'CN',
    trainsOnUserData: true,
    notes:
      'Data is processed on servers in the PRC and is subject to PRC data-access law. Blocked by default.',
  },
  {
    key: 'moonshot-kimi',
    name: 'Kimi',
    vendor: 'Moonshot AI',
    category: 'assistant',
    domains: ['kimi.com', 'kimi.moonshot.cn', 'moonshot.cn'],
    riskWeight: 3,
    defaultPolicy: 'blocked',
    dataRegion: 'CN',
    trainsOnUserData: true,
    notes: 'PRC-hosted.',
  },
  {
    key: 'alibaba-qwen',
    name: 'Qwen',
    vendor: 'Alibaba Cloud',
    category: 'assistant',
    domains: ['qwen.ai', 'chat.qwen.ai', 'tongyi.aliyun.com'],
    riskWeight: 3,
    defaultPolicy: 'blocked',
    dataRegion: 'CN',
    trainsOnUserData: true,
    notes: 'PRC-hosted.',
  },
  {
    key: 'zhipu-glm',
    name: 'ChatGLM',
    vendor: 'Zhipu AI',
    category: 'assistant',
    domains: ['chatglm.cn', 'bigmodel.cn', 'z.ai'],
    riskWeight: 3,
    defaultPolicy: 'blocked',
    dataRegion: 'CN',
    trainsOnUserData: true,
    notes: 'PRC-hosted.',
  },
  {
    key: 'baidu-ernie',
    name: 'ERNIE Bot',
    vendor: 'Baidu',
    category: 'assistant',
    domains: ['yiyan.baidu.com', 'ernie.baidu.com'],
    riskWeight: 3,
    defaultPolicy: 'blocked',
    dataRegion: 'CN',
    trainsOnUserData: true,
    notes: 'PRC-hosted.',
  },

  // ---------------------------------------------------------- AI search ---
  {
    key: 'perplexity',
    name: 'Perplexity',
    vendor: 'Perplexity AI',
    category: 'search',
    domains: ['perplexity.ai'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes: 'Search queries are retained; treat query strings as sensitive.',
  },
  {
    key: 'you-com',
    name: 'You.com',
    vendor: 'You.com',
    category: 'search',
    domains: ['you.com'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes: '',
  },
  {
    key: 'phind',
    name: 'Phind',
    vendor: 'Phind',
    category: 'search',
    domains: ['phind.com'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes: 'Developer-focused search; queries frequently contain proprietary source code.',
  },

  // --------------------------------------------------- coding assistants ---
  {
    key: 'github-copilot',
    name: 'GitHub Copilot',
    vendor: 'GitHub',
    category: 'coding',
    domains: ['api.githubcopilot.com', 'copilot-proxy.githubusercontent.com'],
    riskWeight: 1,
    defaultPolicy: 'approved',
    dataRegion: 'US',
    trainsOnUserData: false,
    notes: 'Business and Enterprise plans exclude prompts and suggestions from training.',
  },
  {
    key: 'cursor',
    name: 'Cursor',
    vendor: 'Anysphere',
    category: 'coding',
    domains: ['cursor.com', 'cursor.sh', 'api2.cursor.sh'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: false,
    notes:
      'Uploads repository context to third-party model providers unless Privacy Mode is enforced org-wide.',
  },
  {
    key: 'windsurf',
    name: 'Windsurf',
    vendor: 'Codeium',
    category: 'coding',
    domains: ['windsurf.com', 'codeium.com'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes: 'Free tier trains on code by default.',
  },
  {
    key: 'tabnine',
    name: 'Tabnine',
    vendor: 'Tabnine',
    category: 'coding',
    domains: ['tabnine.com'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'IL',
    trainsOnUserData: false,
    notes: '',
  },
  {
    key: 'blackbox-ai',
    name: 'Blackbox AI',
    vendor: 'Blackbox',
    category: 'coding',
    domains: ['blackbox.ai', 'useblackbox.io'],
    riskWeight: 4,
    defaultPolicy: 'blocked',
    dataRegion: 'unknown',
    trainsOnUserData: true,
    notes: 'Unvetted vendor with an aggressive browser extension. Blocked by default.',
  },
  {
    key: 'replit-agent',
    name: 'Replit Agent',
    vendor: 'Replit',
    category: 'agent',
    domains: ['replit.com', 'repl.co'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: false,
    notes: '',
  },
  {
    key: 'devin',
    name: 'Devin',
    vendor: 'Cognition',
    category: 'agent',
    domains: ['devin.ai', 'cognition.ai'],
    riskWeight: 3,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: false,
    notes: 'Autonomous agent with repository write access — treat as a privileged identity.',
  },
  {
    key: 'vercel-v0',
    name: 'v0',
    vendor: 'Vercel',
    category: 'coding',
    domains: ['v0.dev', 'v0.app'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes: '',
  },
  {
    key: 'bolt-new',
    name: 'Bolt',
    vendor: 'StackBlitz',
    category: 'coding',
    domains: ['bolt.new'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes: '',
  },
  {
    key: 'lovable',
    name: 'Lovable',
    vendor: 'Lovable',
    category: 'coding',
    domains: ['lovable.dev'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'SE',
    trainsOnUserData: true,
    notes: '',
  },
  {
    key: 'openrouter',
    name: 'OpenRouter',
    vendor: 'OpenRouter',
    category: 'api',
    domains: ['openrouter.ai'],
    riskWeight: 4,
    defaultPolicy: 'unknown',
    dataRegion: 'unknown',
    trainsOnUserData: true,
    notes:
      'Proxies prompts to dozens of downstream providers whose retention policies differ. Effectively an unbounded data-processor list.',
  },
  {
    key: 'groq',
    name: 'Groq Cloud',
    vendor: 'Groq',
    category: 'api',
    domains: ['groq.com'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: false,
    notes: '',
  },
  {
    key: 'together-ai',
    name: 'Together AI',
    vendor: 'Together',
    category: 'api',
    domains: ['together.ai', 'together.xyz'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: false,
    notes: '',
  },
  {
    key: 'replicate',
    name: 'Replicate',
    vendor: 'Replicate',
    category: 'api',
    domains: ['replicate.com'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: false,
    notes: '',
  },
  {
    key: 'huggingface',
    name: 'Hugging Face',
    vendor: 'Hugging Face',
    category: 'api',
    domains: ['huggingface.co', 'hf.co'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: false,
    notes: 'Also a common exfiltration path — private datasets can be pushed to public repos.',
  },
  {
    key: 'poe',
    name: 'Poe',
    vendor: 'Quora',
    category: 'assistant',
    domains: ['poe.com'],
    riskWeight: 3,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes: 'Aggregator over many third-party models.',
  },
  {
    key: 'midjourney',
    name: 'Midjourney',
    vendor: 'Midjourney',
    category: 'image',
    domains: ['midjourney.com'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes: 'Generations are public by default on standard plans.',
  },
  {
    key: 'stability-ai',
    name: 'Stability AI',
    vendor: 'Stability',
    category: 'image',
    domains: ['stability.ai', 'dreamstudio.ai'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'GB',
    trainsOnUserData: false,
    notes: '',
  },
  {
    key: 'leonardo-ai',
    name: 'Leonardo AI',
    vendor: 'Leonardo',
    category: 'image',
    domains: ['leonardo.ai'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'AU',
    trainsOnUserData: true,
    notes: '',
  },
  {
    key: 'runway',
    name: 'Runway',
    vendor: 'Runway',
    category: 'video',
    domains: ['runwayml.com'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes: '',
  },
  {
    key: 'luma-ai',
    name: 'Luma Dream Machine',
    vendor: 'Luma Labs',
    category: 'video',
    domains: ['lumalabs.ai'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes: '',
  },
  {
    key: 'elevenlabs',
    name: 'ElevenLabs',
    vendor: 'ElevenLabs',
    category: 'audio',
    domains: ['elevenlabs.io'],
    riskWeight: 3,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: false,
    notes: 'Voice cloning is a direct impersonation and social-engineering risk.',
  },
  {
    key: 'suno',
    name: 'Suno',
    vendor: 'Suno',
    category: 'audio',
    domains: ['suno.com', 'suno.ai'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes: '',
  },

  // ------------------------------------ productivity / document ingestion ---
  {
    key: 'grammarly',
    name: 'Grammarly',
    vendor: 'Grammarly',
    category: 'other',
    domains: ['grammarly.com', 'grammarly.io'],
    riskWeight: 3,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes:
      'Browser extension transmits full document text, including content typed into internal systems.',
  },
  {
    key: 'quillbot',
    name: 'QuillBot',
    vendor: 'Course Hero',
    category: 'other',
    domains: ['quillbot.com'],
    riskWeight: 3,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes: '',
  },
  {
    key: 'jasper',
    name: 'Jasper',
    vendor: 'Jasper AI',
    category: 'other',
    domains: ['jasper.ai'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: false,
    notes: '',
  },
  {
    key: 'copy-ai',
    name: 'Copy.ai',
    vendor: 'Copy.ai',
    category: 'other',
    domains: ['copy.ai'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes: '',
  },
  {
    key: 'otter-ai',
    name: 'Otter.ai',
    vendor: 'Otter',
    category: 'audio',
    domains: ['otter.ai'],
    riskWeight: 4,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes:
      'Meeting-transcription bots join calls as a participant and capture everything said, including material never intended to be written down.',
  },
  {
    key: 'fireflies-ai',
    name: 'Fireflies.ai',
    vendor: 'Fireflies',
    category: 'audio',
    domains: ['fireflies.ai'],
    riskWeight: 4,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes: 'See Otter.ai — same meeting-capture exposure.',
  },
  {
    key: 'gamma-app',
    name: 'Gamma',
    vendor: 'Gamma',
    category: 'other',
    domains: ['gamma.app'],
    riskWeight: 2,
    defaultPolicy: 'unknown',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes: '',
  },
  {
    key: 'chatpdf',
    name: 'ChatPDF',
    vendor: 'ChatPDF',
    category: 'other',
    domains: ['chatpdf.com'],
    riskWeight: 4,
    defaultPolicy: 'blocked',
    dataRegion: 'unknown',
    trainsOnUserData: true,
    notes:
      'Whole-document upload with no enterprise agreement. A single contract PDF here is a reportable disclosure.',
  },
  {
    key: 'humata-ai',
    name: 'Humata',
    vendor: 'Humata',
    category: 'other',
    domains: ['humata.ai'],
    riskWeight: 4,
    defaultPolicy: 'blocked',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes: 'Whole-document upload. See ChatPDF.',
  },
  {
    key: 'sider-ai',
    name: 'Sider',
    vendor: 'Sider',
    category: 'assistant',
    domains: ['sider.ai'],
    riskWeight: 4,
    defaultPolicy: 'blocked',
    dataRegion: 'unknown',
    trainsOnUserData: true,
    notes: 'Sidebar extension with read access to every page the user opens.',
  },
  {
    key: 'monica-im',
    name: 'Monica',
    vendor: 'Monica',
    category: 'assistant',
    domains: ['monica.im'],
    riskWeight: 4,
    defaultPolicy: 'blocked',
    dataRegion: 'unknown',
    trainsOnUserData: true,
    notes: 'See Sider — same all-pages read scope.',
  },
  {
    key: 'merlin-ai',
    name: 'Merlin',
    vendor: 'Foyer',
    category: 'assistant',
    domains: ['getmerlin.in'],
    riskWeight: 4,
    defaultPolicy: 'blocked',
    dataRegion: 'IN',
    trainsOnUserData: true,
    notes: 'See Sider.',
  },
  {
    key: 'character-ai',
    name: 'Character.AI',
    vendor: 'Character Technologies',
    category: 'assistant',
    domains: ['character.ai', 'c.ai'],
    riskWeight: 3,
    defaultPolicy: 'blocked',
    dataRegion: 'US',
    trainsOnUserData: true,
    notes: 'No legitimate business use case; blocked as an acceptable-use matter.',
  },
];

// Heuristics for hosts the registry has never seen.
export interface HeuristicRule {
  id: string;
  description: string;
  // Tested against the lowercase hostname.
  hostPattern: RegExp;
  // Optional additional constraint on the lowercase path.
  pathPattern?: RegExp;
  confidence: 'medium' | 'high';
}

export const HEURISTIC_RULES: readonly HeuristicRule[] = [
  {
    id: 'gpt-in-host',
    description: 'Hostname contains a GPT/LLM product token',
    hostPattern: /(^|[.-])(chatgpt|gpt[0-9]?|llm|llama|mixtral|claude|gemini)([.-]|$)/,
    confidence: 'high',
  },
  {
    id: 'ai-subdomain',
    description: 'Dedicated AI subdomain (ai.example.com, chat.example.com)',
    hostPattern: /^(ai|chat|copilot|assistant|bot|genai)\./,
    confidence: 'medium',
  },
  {
    id: 'dot-ai-tld',
    description: 'Registered under the .ai TLD',
    hostPattern: /\.ai$/,
    confidence: 'medium',
  },
  {
    id: 'ai-chat-path',
    description: 'AI-shaped host serving a chat or completion endpoint',
    hostPattern: /(ai|ml)([.-]|$)/,
    pathPattern: /\/(chat|completions?|prompt|generate|inference)(\/|$)/,
    confidence: 'high',
  },
];
export const HEURISTIC_ALLOWLIST: readonly string[] = [
  'notion.ai',
  'jira.ai',
  'atlassian.ai',
  'ai.google',
  'chat.google.com',
  'chat.whatsapp.com',
  'chat.zoom.us',
  'chat.slack.com',
  'ai.meta.com',
  'assistant.microsoft.com',
  'bot.teams.microsoft.com',
];
