import { Schema, model, type HydratedDocument, type InferSchemaType } from 'mongoose';
import { POLICY_STATUSES, RISK_BANDS } from '@shadowscan/shared';

/**
 * riskreports - a frozen snapshot of the posture over a time window.
 *
 * A report is *not* a saved query. It stores the computed numbers, because the
 * whole point of an audit artefact is that re-opening it next quarter shows what
 * it showed when it was signed. If it re-ran the aggregation on view, deleting an
 * upload would silently rewrite history.
 *
 * | field           | why it exists                                                 |
 * |-----------------|---------------------------------------------------------------|
 * | period*         | inclusive window the numbers describe.                        |
 * | score / band    | normalised 0-100 posture and its band at generation time.     |
 * | summary         | the headline counts rendered on page 1 of the PDF.            |
 * | topProviders    | tool inventory for the window.                                |
 * | topActors       | highest-risk individuals, pseudonymous.                       |
 * | recommendations | generated by deterministic rules over the summary - see       |
 * |                 | engine/recommendations.ts. No LLM: an auditor needs a         |
 * |                 | reproducible finding, not a plausible sentence.               |
 */
const summarySchema = new Schema(
  {
    totalEvents: { type: Number, required: true, default: 0 },
    aiRequests: { type: Number, required: true, default: 0 },
    shadowAiRequests: { type: Number, required: true, default: 0 },
    approvedRequests: { type: Number, required: true, default: 0 },
    uniqueActors: { type: Number, required: true, default: 0 },
    uniqueProviders: { type: Number, required: true, default: 0 },
    sensitiveHits: { type: Number, required: true, default: 0 },
  },
  { _id: false },
);

const topProviderSchema = new Schema(
  {
    key: { type: String, required: true },
    name: { type: String, required: true },
    requests: { type: Number, required: true },
    policy: { type: String, enum: POLICY_STATUSES, required: true },
  },
  { _id: false },
);

const topActorSchema = new Schema(
  {
    actor: { type: String, required: true },
    requests: { type: Number, required: true },
    score: { type: Number, required: true },
    band: { type: String, enum: RISK_BANDS, required: true },
  },
  { _id: false },
);

const recommendationSchema = new Schema(
  {
    severity: { type: String, enum: RISK_BANDS, required: true },
    title: { type: String, required: true, maxlength: 160 },
    detail: { type: String, required: true, maxlength: 1000 },
  },
  { _id: false },
);

const riskReportSchema = new Schema(
  {
    title: { type: String, required: true, maxlength: 160 },
    periodStart: { type: Date, required: true },
    periodEnd: { type: Date, required: true },
    score: { type: Number, required: true, min: 0, max: 100 },
    band: { type: String, enum: RISK_BANDS, required: true },
    summary: { type: summarySchema, required: true },
    topProviders: { type: [topProviderSchema], default: [] },
    topActors: { type: [topActorSchema], default: [] },
    recommendations: { type: [recommendationSchema], default: [] },
    generatedBy: { type: Schema.Types.ObjectId, ref: 'User', default: null },
  },
  { timestamps: true },
);

riskReportSchema.index({ createdAt: -1 });

export type RiskReportAttrs = InferSchemaType<typeof riskReportSchema>;

export type RiskReportDoc = HydratedDocument<RiskReportAttrs>;

export const RiskReport = model('RiskReport', riskReportSchema);
